import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    nav: {
      nexus: 'NEXUS', about: 'ABOUT', stack: 'STACK', trajectory: 'TRAJECTORY', writeups: 'WRITEUPS', connect: 'CONNECT',
      motionOn: 'MOTION: ON', motionOff: 'MOTION: OFF',
    },
    about: {
      label: 'OPERATOR_PROFILE',
      title1: 'ABOUT', title2: 'THE_ARCHITECT',
      bioPath: 'cat about.md',
      bio1: 'I am Parsa Sariri Ajili — a 19-year-old network engineering student with a deep passion for building and securing digital infrastructure.',
      bio2: 'My journey began with hardware and operating systems, evolving into network architecture across Cisco, MikroTik, and Microsoft ecosystems. Along the way, I mastered Linux administration, Python automation, and virtualization technologies.',
      bio3: 'Currently preparing to pivot into cybersecurity — transforming my networking expertise into proactive defense, threat analysis, and impenetrable security architecture.',
      statsCerts: 'CERTIFICATIONS', statsDomains: 'DOMAINS', statsAge: 'YEARS OLD', statsLearning: 'LEARNING',
    },
    hero: {
      systemOnline: 'SYSTEM ONLINE',
      tagline: 'Network Engineering & Cybersecurity Specialist',
      birthTag: 'B.2007.06.16',
      statusTag: 'STATUS: NETWORK_ARCHITECT',
      pivotTag: 'PIVOT → CYBER_SEC',
      viewStack: 'VIEW_STACK',
      initiateContact: 'INITIATE_CONTACT',
      scrollToTraverse: 'SCROLL_TO_TRAVERSE',
    },
    skills: {
      label: 'STACK_HIERARCHY',
      title1: 'CERTIFICATION',
      title2: 'RACK',
      description: 'Each blade represents a layer of technical mastery. Click to inspect the protocols within.',
      rackInfo: '/dev/certification_rack — 10 BLADES MOUNTED',
      masteryPoints: 'MASTERY_POINTS:',
    },
    certs: {
      aplus: { name: 'CompTIA A+', category: 'Infrastructure', mastery: ['Hardware diagnostics', 'PC assembly & repair', 'Mobile devices', 'Operating systems', 'Troubleshooting methodology'] },
      netplus: { name: 'CompTIA Network+', category: 'Networking', mastery: ['OSI & TCP/IP models', 'Subnetting & VLANs', 'Routing & switching', 'Network security basics', 'Wireless protocols'] },
      mcsa: { name: 'Microsoft MCSA', category: 'Microsoft', mastery: ['Windows Server administration', 'Active Directory', 'Group Policy', 'DNS/DHCP on Windows', 'Hyper-V'] },
      lpic1: { name: 'Linux LPIC-1', category: 'Linux', mastery: ['Command-line proficiency', 'File systems & permissions', 'Process management', 'Bash scripting', 'Package management'] },
      pynet: { name: 'Python for Network Engineers', category: 'Programming', mastery: ['Network automation', 'Netmiko & NAPALM', 'API interactions', 'Configuration management', 'Data parsing & analysis'] },
      ccna: { name: 'Cisco CCNA', category: 'Networking', mastery: ['IOS configuration', 'VLANs & trunking', 'OSPF & static routing', 'ACLs & NAT', 'Device security'] },
      mtcna: { name: 'MikroTik MTCNA', category: 'Networking', mastery: ['RouterOS administration', 'Firewall & NAT', 'Wireless & CAPsMAN', 'Hotspot & PPPoE', 'Queues & QoS'] },
      lpic2: { name: 'Linux LPIC-2', category: 'Linux', mastery: ['Advanced system administration', 'Kernel & boot process', 'DNS & mail servers', 'Web services', 'System security hardening'] },
      vcp: { name: 'Virtualization VCP', category: 'Virtualization', mastery: ['VMware vSphere', 'VM lifecycle management', 'Resource pools', 'vMotion & HA', 'Storage management'] },
      bm: { name: 'Backup and Monitoring', category: 'Infrastructure', mastery: ['Backup strategies', 'Disaster recovery', 'Monitoring tools', 'Alerting & thresholds', 'Log analysis'] },
    },
    trajectory: {
      label: 'THE_TRAJECTORY',
      titleFrom: 'FROM', titleNetwork: 'NETWORK', titleTo: 'TO', titleSecurity: 'SECURITY',
      subtitle: 'A continuous evolution — building the infrastructure today, securing it tomorrow.',
      currentState: 'CURRENT_STATE', networkMastery: 'Network Mastery',
      nextVector: 'NEXT_VECTOR', cybersecurity: 'Cybersecurity',
      currentGrid: { routing: 'Routing & Switching', infra: 'Infrastructure', server: 'Server Administration', defense: 'Network Defense' },
      futureGrid: { pentest: 'Penetration Testing', threat: 'Threat Analysis', secArch: 'Sec Architecture', incident: 'Incident Response' },
      currentDesc: 'Currently studying network engineering with deep hands-on expertise across Cisco, MikroTik, Linux, and Microsoft ecosystems. 10 certifications and counting.',
      futureDesc: 'Next phase: diving deep into cybersecurity — transforming network knowledge into impenetrable defense systems and proactive threat intelligence.',
      masteryLevel: 'MASTERY_LEVEL', inProgress: 'IN_PROGRESS',
    },
    contact: {
      label: 'THE_PROTOCOL',
      title1: 'ESTABLISH', title2: 'CONNECTION',
      description: 'Initialize a secure data transmission. All inputs are encrypted and logged.',
      inputName: 'INPUT_NAME:', inputEmail: 'INPUT_EMAIL:', inputMessage: 'INPUT_MESSAGE:',
      namePlaceholder: 'enter your name...', emailPlaceholder: 'enter your email...', messagePlaceholder: 'type your message...',
      execute: 'EXECUTE_SEND', transmitting: 'TRANSMITTING...', complete: 'TRANSMISSION COMPLETE',
      shellPrompt: 'parsa@secure-shell:~$',
      toastTitle: 'TRANSMISSION COMPLETE', toastDesc: 'Message received. I will respond shortly.',
      errorTitle: 'TRANSMISSION FAILED', errorDesc: 'Something went wrong. Please try again.',
    },
    writeups: {
      badge: 'LAB NOTEBOOK // REPRODUCIBLE RESEARCH & THREAT HUNTING',
      title1: 'TECHNICAL INVESTIGATIONS', title2: '& LAB REPORTS',
      subtitle: 'Incident triage, KQL threat hunting across billion-row telemetry, and systems engineering — documented the way it happened, with first-hand evidence and reproducible steps.',
      categories: {
        all: 'ALL',
        threat: 'THREAT HUNTING (KQL)',
        dfir: 'DFIR',
        infra: 'INFRASTRUCTURE',
        malware: 'MALWARE',
      },
      emptyTitle: 'NO_ENTRIES_IN_THIS_CATEGORY',
      emptyDesc: 'Nothing logged here yet — new investigations land in this category as they wrap up.',
      featuredBadge: 'CREDLY 100% GOLD AWARD',
      featuredEyebrow: 'FEATURED CASE FILE',
      readFull: 'Read Full Investigation',
      viewRepo: 'View Repository',
      viewCredential: 'View Credential',
      difficulty: 'Difficulty',
      status: 'Status',
      backToIndex: 'Back to writeups index',
      closeReader: 'Close reader',
      toolsUsed: 'Tools Used',
      sections: {
        abstract: 'Abstract & Executive Summary',
        problem: 'Problem Statement',
        environment: 'Environment & Setup',
        evidence: 'Verifiable Evidence Log',
        timeline: 'Reconstructed Timeline',
        methodology: 'Methodology & KQL Patterns',
        findings: 'Root Cause Findings & Limitations',
      },
      limitationLabel: 'LIMITATION',
      reproductionLabel: 'REPRODUCTION',
      viewAllLink: 'View All Writeups & Lab Notebook',
      catalogBadge: 'FULL CASE INDEX',
      catalogSubtitle: 'Every logged investigation, filterable by discipline.',
      backToWriteups: 'Back to Writeups',
      backHome: 'Back to homepage',
      copyCode: 'Copy',
      copied: 'Copied!',
      credly: {
        verified: 'Verified Credential',
        viewOnCredly: 'View on Credly',
        badgeTitle: 'Kusto Detective Gold Star!',
        issuer: 'Issued by Microsoft Azure Data Explorer',
      },
      credentials: {
        rackLabel: 'VERIFIED CREDENTIALS',
        goldStar: 'Credly Gold Star (100% Award)',
        principalDetective: 'Principal Detective Rank',
        appliedSkills: 'Microsoft Applied Skills — APL-5004 (Defender XDR)',
        verifyAppliedSkills: 'Verify on Microsoft Learn',
        viewAllBadges: 'All 11 Official Microsoft KDA Badges on Credly',
      },
      notFoundTitle: 'CASE_FILE_NOT_FOUND',
      notFoundDesc: 'No investigation is logged at this address. It may have been renamed or archived.',
      metaTitleSuffix: 'Lab Notebook — Parsa Sariri',
      kda: {
        title: 'Echoes of Deception: Solving All 11 Cases of the Kusto Detective Agency, Season 2',
        description: 'A full case log of the Season 2 Azure Data Explorer investigation game — resolving all eleven cases across 2.18M+ MachineLogs rows using graph traversal, stateful sequence matching, and bitwise correlation in KQL.',
        status: 'Case Log / Completed Investigation — 100% Gold Award',
        metrics: {
          cases: 'CASES RESOLVED',
          logs: 'MACHINELOGS TRAVERSED',
          graph: 'LATERAL MOVEMENT MAPPING',
          solver: 'STATEFUL PATTERN SOLVER',
        },
        content: {
          abstract: 'This case log documents the complete resolution of the Kusto Detective Agency Season 2 campaign, "Echoes of Deception" — an eleven-case investigative exercise built on Azure Data Explorer (ADX) and the Kusto Query Language (KQL). Each case supplied a narrative brief and a slice of a shared, multi-million-row telemetry dataset; the task was to isolate the responsible entity, action, or anomaly using nothing but KQL against the live cluster. All eleven cases were solved without external tooling, earning the Principal Detective Agent rank and a 100% Gold Award on Credly.',
          problem: 'The season-long dataset centered on the MachineLogs table — a synthetic but densely structured telemetry stream simulating process activity, authentication events, and inter-machine communication across a fictional network of compromised and clean hosts. Each case narrowed the search space differently: some asked for a single anomalous actor buried in millions of rows, others required reconstructing a multi-hop chain of lateral movement, and a few encoded the answer inside bitmasked flag fields that had to be decoded arithmetically rather than filtered directly.',
          environment: [
            'Platform: Azure Data Explorer (ADX) — Kusto Detective Agency Season 2 cluster',
            'Primary table: MachineLogs (2.18M+ rows across the full season)',
            'Query surface: Kusto Query Language (KQL) only — no external scripting or offline processing',
            'Session tooling: ADX web query editor, saved query history for case reproducibility',
          ],
          evidence: [
            { event: 'Row-scale confirmation', timestamp: 'Season baseline', detail: 'MachineLogs | summarize count() returned a working set of 2,183,441 rows, confirming the dataset required aggregation-first strategies rather than manual row inspection.' },
            { event: 'Lateral movement graph build', timestamp: 'Cases 6-8', detail: 'make-graph SourceMachine --> TargetMachine with edge property Timestamp, followed by graph-match to isolate multi-hop paths matching the case narrative\'s described intrusion chain.' },
            { event: 'Bitmask decode pass', timestamp: 'Case 10', detail: 'extend FlagBits = bitset_count_ones(StatusMask) combined with binary_and() filtering to isolate the single machine whose status flags matched the case\'s hidden condition.' },
          ],
          timeline: [
            '[CASES 1-3] ─── Baseline aggregation & filtering fluency (summarize, where, project)',
            '       │',
            '[CASES 4-5] ─── Time-window correlation across authentication and process events',
            '       │',
            '[CASES 6-8] ─── make-graph + graph-match for multi-hop lateral movement chains',
            '       │',
            '[CASE 9]    ─── scan operator for stateful, order-dependent sequence detection',
            '       │',
            '[CASE 10]   ─── Bitwise decoding of packed status flags with bitset_count_ones',
            '       │',
            '[CASE 11]   ─── Final synthesis case combining graph traversal with bitmask evidence',
            '       │',
            '[RESULT]    ─── 11 / 11 cases resolved — Principal Detective Agent, 100% Gold Award',
          ],
          methodology: [
            'make-graph: builds an in-memory graph from tabular edges (SourceMachine, TargetMachine) so that graph-match can search for path patterns — the core technique for reconstructing lateral movement across hosts without manually joining the table against itself for every hop.',
            'scan operator: evaluates rows in order while carrying state forward between them, which made it possible to detect sequences where the meaning of a row depended on what came immediately before it — something a stateless where clause cannot express.',
            'bitset_count_ones / binary_and: decode packed integer flag fields bit by bit, letting a single StatusMask column stand in for many boolean conditions at once, and isolate the row whose bit pattern matched the case\'s described condition.',
          ],
          findings: [
            'All eleven cases resolved using KQL exclusively against the live ADX cluster, with no external data processing.',
            'The recurring engineering pattern across the hardest cases was graph reconstruction (make-graph) paired with stateful sequence detection (scan) — the same combination used in real lateral-movement threat hunting.',
            'Bitmask decoding (Case 10) proved that dense status-flag columns can hide structured, queryable signal instead of being treated as opaque.',
          ],
          limitations: 'This was a training and assessment environment (Kusto Detective Agency), not a live production incident — the dataset is synthetic and the "adversary" behavior is scripted by the case designers. The value is in the transferable KQL technique set (graph traversal, stateful scanning, bitwise correlation), not in claiming a real-world incident response.',
          reproduction: 'Full query history and case-by-case notes are published in the linked GitHub repository for anyone reproducing the investigation against their own Kusto Detective Agency Season 2 instance.',
        },
      },
      hayabusa: {
        title: 'From Event Log to Attack Timeline: A Reproducible Windows Triage Workflow with Hayabusa',
        description: 'A structured engineering postmortem investigating a simulated initial compromise. Correlating EVTX telemetry, Sigma rule detections, PowerShell script block logs, and process execution trees into a verifiable timeline.',
        status: 'Lab Research / Postmortem',
        content: {
          abstract: 'This technical lab report documents an end-to-end digital forensics and incident response (DFIR) investigation conducted on a compromised Windows workstation. Using high-speed Rust-based forensic triage tooling (Hayabusa) correlated with Windows Security, System, and PowerShell Script Block event logs, the complete attack timeline is reconstructed from initial execution to credential harvesting and lateral probing.',
          problem: 'During routine threat hunting, an anomalous outbound SMB connection was detected. Raw event log artifacts (.evtx) were collected from WORKSTATION-04. Objective: determine the initial access mechanism, child process lineage, and validate credential access attempts.',
          environment: [
            'Target OS: Windows 10 Enterprise (Build 19045, x64)',
            'Triage Analysis Host: Linux Kernel 7.0 / Ubuntu 24.04',
            'Tooling: Hayabusa v2.17.0 (Sigma v0.22 ruleset), EvtxECmd v1.5.0, custom Python normalizer',
          ],
          evidence: [
            { event: 'EID 4688 (Process Creation)', timestamp: '14:22:08.114 UTC', detail: 'WINWORD.EXE spawned cmd.exe -> powershell.exe with an encoded command argument, consistent with a phishing macro execution chain.' },
            { event: 'Decoded payload', timestamp: '14:22:12.430 UTC', detail: 'Invoke-WebRequest against an external host retrieved a second-stage PowerShell script to a temp path and executed it immediately.' },
            { event: 'LSASS handle access (Sysmon 10)', timestamp: '14:25:31.002 UTC', detail: 'Target lsass.exe opened with a read-limited-information access mask — flagged as a credential dumping attempt pattern.' },
          ],
          timeline: [
            '[14:22:08 UTC] ─── WINWORD.EXE spawns cmd.exe (phishing macro execution)',
            '       │',
            '[14:22:12 UTC] ─── PowerShell executes stage-2 download cradle',
            '       │',
            '[14:23:45 UTC] ─── Reconnaissance: whoami /all & net user /domain',
            '       │',
            '[14:25:31 UTC] ─── LSASS handle opened (credential dumping attempt)',
            '       │',
            '[14:26:10 UTC] ─── Process terminated by EDR / host isolated',
          ],
          methodology: [
            'Phase 1 — High-speed triage with Hayabusa: hayabusa csv-timeline against the collected evidence, filtered to medium severity and above.',
            'Phase 2 — PowerShell Script Block analysis: filtering Event ID 4104 for AMSI-logged script blocks to recover the decoded payload.',
            'Phase 3 — Process execution tree mapping: parent-child correlation on Event ID 4688 with full command-line auditing.',
          ],
          findings: [
            'Root cause: malicious macro execution initiated secondary payload staging.',
            'Credential exposure: a read handle was opened against LSASS; credential invalidation was required.',
            'Lateral probing: the host was isolated before any successful lateral authentication occurred.',
          ],
          limitations: 'Memory was not captured at the exact millisecond of in-memory injection, and C2 TLS traffic was left uninspected without a host TLS key log.',
          reproduction: 'A sanitized EVTX test bundle is available. Run Hayabusa against it with the referenced Sigma rule ID to verify detection confidence.',
        },
      },
    },
    footer: {
      role: 'NETWORK ENGINEER // INFRASTRUCTURE SPECIALIST',
      copyright: '© 2026 PARSA SARIRI AJILI // ALL_PROTOCOLS_RESERVED',
      builtWith: 'Built with 💙 by Parsa Sariri Ajili',
    },
  },
  fa: {
    nav: {
      nexus: 'هسته', about: 'درباره', stack: 'مهارت‌ها', trajectory: 'مسیر', writeups: 'گزارش‌های فنی', connect: 'ارتباط',
      motionOn: 'حرکت: روشن', motionOff: 'حرکت: خاموش',
    },
    about: {
      label: 'پروفایل اپراتور',
      title1: 'درباره', title2: 'معمار',
      bioPath: 'cat about.md',
      bio1: 'من پارسا سریری آجیلی هستم — دانشجوی ۱۹ ساله مهندسی شبکه با علاقه‌ای عمیق به ساخت و تأمین امنیت زیرساخت‌های دیجیتال.',
      bio2: 'مسیر من از سخت‌افزار و سیستم‌عامل‌ها آغاز شد و به معماری شبکه در اکوسیستم‌های سیسکو، میکروتیک و مایکروسافت رسید. در این مسیر، مدیریت لینوکس، اتوماسیون پایتون و تکنولوژی‌های مجازی‌سازی را تسلط یافتم.',
      bio3: 'در حال حاضر برای ورود به حوزه امنیت سایبری آماده می‌شوم — تبدیل تخصص شبکه‌ام به دفاع فعال، تحلیل تهدید و معماری امنیت نفوذناپذیر.',
      statsCerts: 'گواهینامه', statsDomains: 'حوزه', statsAge: 'سال سن', statsLearning: 'یادگیری',
    },
    hero: {
      systemOnline: 'سیستم آنلاین',
      tagline: 'متخصص مهندسی شبکه و امنیت سایبری',
      birthTag: 'B.2007.06.16',
      statusTag: 'وضعیت: معمار شبکه',
      pivotTag: 'مسیر → امنیت سایبری',
      viewStack: 'مشاهده مهارت‌ها',
      initiateContact: 'برقراری ارتباط',
      scrollToTraverse: 'برای ادامه اسکرول کنید',
    },
    skills: {
      label: 'سلسله‌مراتب مهارت‌ها',
      title1: 'رک',
      title2: 'گواهینامه‌ها',
      description: 'هر تیغه نشان‌دهنده یک لایه از تسلط فنی است. برای بررسی پروتکل‌ها کلیک کنید.',
      rackInfo: '/dev/certification_rack — ۱۰ تیغه نصب شده',
      masteryPoints: 'نقاط تسلط:',
    },
    certs: {
      aplus: { name: 'CompTIA A+', category: 'زیرساخت', mastery: ['تشخیص سخت‌افزار', 'مونتاژ و تعمیر کامپیوتر', 'دستگاه‌های موبایل', 'سیستم‌عامل‌ها', 'روش‌شناسی عیب‌یابی'] },
      netplus: { name: 'CompTIA Network+', category: 'شبکه', mastery: ['مدل‌های OSI و TCP/IP', 'سابنت و VLAN', 'مسیریابی و سوئیچینگ', 'مبانی امنیت شبکه', 'پروتکل‌های بی‌سیم'] },
      mcsa: { name: 'Microsoft MCSA', category: 'مایکروسافت', mastery: ['مدیریت Windows Server', 'اکتیو دایرکتوری', 'Group Policy', 'DNS/DHCP در ویندوز', 'Hyper-V'] },
      lpic1: { name: 'Linux LPIC-1', category: 'لینوکس', mastery: ['تسلط بر خط فرمان', 'سیستم فایل و مجوزها', 'مدیریت پردازش‌ها', 'اسکریپت‌نویسی Bash', 'مدیریت بسته‌ها'] },
      pynet: { name: 'Python for Network Engineers', category: 'برنامه‌نویسی', mastery: ['اتوماسیون شبکه', 'Netmiko و NAPALM', 'تعامل با API', 'مدیریت پیکربندی', 'پردازش و تحلیل داده'] },
      ccna: { name: 'Cisco CCNA', category: 'شبکه', mastery: ['پیکربندی IOS', 'VLAN و Trunking', 'مسیریابی OSPF و استاتیک', 'ACL و NAT', 'امنیت دستگاه‌ها'] },
      mtcna: { name: 'MikroTik MTCNA', category: 'شبکه', mastery: ['مدیریت RouterOS', 'فایروال و NAT', 'بی‌سیم و CAPsMAN', 'Hotspot و PPPoE', 'صف‌ها و QoS'] },
      lpic2: { name: 'Linux LPIC-2', category: 'لینوکس', mastery: ['مدیریت پیشرفته سیستم', 'کرنل و فرآیند بوت', 'سرورهای DNS و ایمیل', 'سرویس‌های وب', 'سخت‌سازی امنیت سیستم'] },
      vcp: { name: 'Virtualization VCP', category: 'مجازی‌سازی', mastery: ['VMware vSphere', 'مدیریت چرخه حیات VM', 'استخر منابع', 'vMotion و HA', 'مدیریت ذخیره‌سازی'] },
      bm: { name: 'Backup and Monitoring', category: 'زیرساخت', mastery: ['استراتژی‌های پشتیبان‌گیری', 'بازیابی پس از فاجعه', 'ابزارهای مانیتورینگ', 'هشدار و آستانه‌ها', 'تحلیل لاگ'] },
    },
    trajectory: {
      label: 'مسیر',
      titleFrom: 'از', titleNetwork: 'شبکه', titleTo: 'تا', titleSecurity: 'امنیت',
      subtitle: 'تکامل مستمر — ساختن زیرساخت امروز، تأمین امنیت فردا.',
      currentState: 'وضعیت فعلی', networkMastery: 'تسلط بر شبکه',
      nextVector: 'مسیر بعدی', cybersecurity: 'امنیت سایبری',
      currentGrid: { routing: 'مسیریابی و سوئیچینگ', infra: 'زیرساخت', server: 'مدیریت سرور', defense: 'دفاع شبکه' },
      futureGrid: { pentest: 'تست نفوذ', threat: 'تحلیل تهدید', secArch: 'معماری امنیت', incident: 'پاسخ به حادثه' },
      currentDesc: 'در حال تحصیل مهندسی شبکه با تخصص عملی گسترده در اکوسیستم‌های سیسکو، میکروتیک، لینوکس و مایکروسافت. ۱۰ گواهینامه و در حال افزایش.',
      futureDesc: 'مرحله بعد: غوطه‌وری عمیق در امنیت سایبری — تبدیل دانش شبکه به سیستم‌های دفاعی نفوذناپذیر و هوش تهدیدات فعال.',
      masteryLevel: 'سطح تسلط', inProgress: 'در حال انجام',
    },
    contact: {
      label: 'پروتکل',
      title1: 'برقراری', title2: 'ارتباط',
      description: 'یک انتقال داده امن را آغاز کنید. تمام ورودی‌ها رمزگذاری و ثبت می‌شوند.',
      inputName: 'نام:', inputEmail: 'ایمیل:', inputMessage: 'پیام:',
      namePlaceholder: 'نام خود را وارد کنید...', emailPlaceholder: 'ایمیل خود را وارد کنید...', messagePlaceholder: 'پیام خود را تایپ کنید...',
      execute: 'ارسال', transmitting: 'در حال ارسال...', complete: 'ارسال کامل شد',
      shellPrompt: 'parsa@secure-shell:~$',
      toastTitle: 'ارسال کامل شد', toastDesc: 'پیام دریافت شد. به‌زودی پاسخ خواهم داد.',
      errorTitle: 'ارسال ناموفق', errorDesc: 'مشکلی پیش آمد. لطفاً دوباره تلاش کنید.',
    },
    writeups: {
      badge: 'دفترچه آزمایشگاه // پژوهش بازتولیدپذیر و شکار تهدید',
      title1: 'گزارش‌های فنی', title2: 'و تحقیقات آزمایشگاهی',
      subtitle: 'تریاژ حوادث، شکار تهدید با KQL روی بیگ‌دیتای میلیونی، و مهندسی سیستم‌ها — همان‌طور که رخ داده مستند شده، همراه با شواهد دست اول و مراحل قابل بازتولید.',
      categories: {
        all: 'همه',
        threat: 'شکار تهدید (KQL)',
        dfir: 'دیفایر (DFIR)',
        infra: 'زیرساخت',
        malware: 'بدافزار',
      },
      emptyTitle: 'هیچ موردی در این دسته نیست',
      emptyDesc: 'هنوز چیزی در این دسته ثبت نشده — با تکمیل تحقیقات جدید، این بخش پر خواهد شد.',
      featuredBadge: 'مدال طلای ۱۰۰٪ Credly',
      featuredEyebrow: 'پرونده ویژه',
      readFull: 'مطالعه کامل گزارش',
      viewRepo: 'مشاهده ریپازیتوری',
      viewCredential: 'مشاهده مدرک',
      difficulty: 'سطح دشواری',
      status: 'وضعیت',
      backToIndex: 'بازگشت به فهرست گزارش‌ها',
      closeReader: 'بستن',
      toolsUsed: 'ابزارهای استفاده‌شده',
      sections: {
        abstract: 'چکیده و خلاصه اجرایی',
        problem: 'صورت مسئله',
        environment: 'محیط و راه‌اندازی',
        evidence: 'لاگ شواهد قطعی',
        timeline: 'تایم‌لاین بازسازی‌شده',
        methodology: 'روش‌شناسی و الگوهای KQL',
        findings: 'یافته‌های علت ریشه‌ای و محدودیت‌ها',
      },
      limitationLabel: 'محدودیت',
      reproductionLabel: 'بازتولید',
      viewAllLink: 'مشاهده همه گزارش‌ها و دفترچه آزمایشگاه',
      catalogBadge: 'فهرست کامل پرونده‌ها',
      catalogSubtitle: 'تمام تحقیقات ثبت‌شده، قابل فیلتر بر اساس حوزه.',
      backToWriteups: 'بازگشت به گزارش‌های فنی',
      backHome: 'بازگشت به صفحه اصلی',
      copyCode: 'کپی',
      copied: 'کپی شد!',
      credly: {
        verified: 'مدرک تاییدشده',
        viewOnCredly: 'مشاهده در Credly',
        badgeTitle: 'Kusto Detective Gold Star!',
        issuer: 'صادرشده توسط Microsoft Azure Data Explorer',
      },
      credentials: {
        rackLabel: 'مدارک و نشان‌های تاییدشده',
        goldStar: 'مدال طلای Credly (۱۰۰٪ کامل)',
        principalDetective: 'رنک کارآگاه ارشد (Principal Detective)',
        appliedSkills: 'مدرک مایکروسافت Applied Skills — APL-5004 (Defender XDR)',
        verifyAppliedSkills: 'تایید در Microsoft Learn',
        viewAllBadges: 'مشاهده هر ۱۱ نشان رسمی KDA مایکروسافت در Credly',
      },
      notFoundTitle: 'پرونده یافت نشد',
      notFoundDesc: 'هیچ تحقیقی در این آدرس ثبت نشده است. ممکن است تغییر نام یافته یا بایگانی شده باشد.',
      metaTitleSuffix: 'دفترچه آزمایشگاه — پارسا سریری',
      kda: {
        title: 'پژواک فریب: حل هر ۱۱ پرونده فصل دوم Kusto Detective Agency',
        description: 'گزارش کامل بازی تحقیقاتی فصل دوم Azure Data Explorer — حل هر یازده پرونده روی بیش از ۲.۱۸ میلیون ردیف تله‌متری MachineLogs با استفاده از پیمایش گراف، تطبیق دنباله‌ای حالت‌دار و همبستگی بیتی در KQL.',
        status: 'گزارش پرونده / تحقیق تکمیل‌شده — مدال طلای ۱۰۰٪',
        metrics: {
          cases: 'پرونده حل‌شده',
          logs: 'ردیف تله‌متری پیموده‌شده',
          graph: 'نگاشت حرکت جانبی',
          solver: 'حل‌کننده الگوی حالت‌دار',
        },
        content: {
          abstract: 'این گزارش، حل کامل کارزار فصل دوم Kusto Detective Agency با عنوان «پژواک فریب» را مستند می‌کند — تمرینی تحقیقاتی شامل یازده پرونده، مبتنی بر Azure Data Explorer (ADX) و زبان Kusto Query Language (KQL). هر پرونده یک شرح روایی و بخشی از یک مجموعه‌داده تله‌متری میلیونی مشترک ارائه می‌داد؛ وظیفه، شناسایی عامل، عملیات یا ناهنجاری مسئول تنها با استفاده از KQL روی کلاستر زنده بود. هر یازده پرونده بدون هیچ ابزار خارجی حل شد و رتبه Principal Detective Agent و مدال طلای ۱۰۰٪ در Credly کسب شد.',
          problem: 'مجموعه‌داده فصل، حول جدول MachineLogs شکل گرفته بود — جریانی مصنوعی اما ساختاریافته از تله‌متری که فعالیت پردازش، رویدادهای احراز هویت و ارتباط بین ماشین‌ها را در یک شبکه فرضی از میزبان‌های آلوده و سالم شبیه‌سازی می‌کرد. هر پرونده فضای جست‌وجو را به شکلی متفاوت محدود می‌کرد: برخی به دنبال یک عامل ناهنجار در میان میلیون‌ها ردیف بودند، برخی نیازمند بازسازی زنجیره چندمرحله‌ای حرکت جانبی بودند و چند پرونده پاسخ را درون فیلدهای بیتی رمزگذاری کرده بودند که باید به‌صورت محاسباتی رمزگشایی می‌شد.',
          environment: [
            'پلتفرم: Azure Data Explorer (ADX) — کلاستر فصل دوم Kusto Detective Agency',
            'جدول اصلی: MachineLogs (بیش از ۲.۱۸ میلیون ردیف در کل فصل)',
            'سطح پرس‌وجو: تنها Kusto Query Language (KQL) — بدون اسکریپت خارجی یا پردازش آفلاین',
            'ابزار نشست: ویرایشگر پرس‌وجوی وب ADX، تاریخچه پرس‌وجوهای ذخیره‌شده برای بازتولیدپذیری هر پرونده',
          ],
          evidence: [
            { event: 'تایید مقیاس ردیف‌ها', timestamp: 'خط پایه فصل', detail: 'MachineLogs | summarize count() مجموعه‌ای ۲,۱۸۳,۴۴۱ ردیفی را بازگرداند که نشان می‌داد استراتژی باید مبتنی بر تجمیع باشد نه بازرسی دستی ردیف‌به‌ردیف.' },
            { event: 'ساخت گراف حرکت جانبی', timestamp: 'پرونده‌های ۶ تا ۸', detail: 'make-graph SourceMachine --> TargetMachine با ویژگی یال Timestamp، سپس graph-match برای جداسازی مسیرهای چندمرحله‌ای منطبق با روایت پرونده.' },
            { event: 'رمزگشایی بیت‌مسک', timestamp: 'پرونده ۱۰', detail: 'extend FlagBits = bitset_count_ones(StatusMask) همراه با فیلتر binary_and() برای جداسازی تنها ماشینی که پرچم‌های وضعیتش با شرط پنهان پرونده مطابقت داشت.' },
          ],
          timeline: [
            '[پرونده ۱-۳] ─── مهارت پایه در تجمیع و فیلترینگ (summarize، where، project)',
            '       │',
            '[پرونده ۴-۵] ─── همبستگی بازه زمانی میان رویدادهای احراز هویت و پردازش',
            '       │',
            '[پرونده ۶-۸] ─── make-graph و graph-match برای زنجیره‌های چندمرحله‌ای حرکت جانبی',
            '       │',
            '[پرونده ۹]   ─── اپراتور scan برای تشخیص دنباله‌ای حالت‌دار و وابسته به ترتیب',
            '       │',
            '[پرونده ۱۰]  ─── رمزگشایی بیتی پرچم‌های وضعیت فشرده با bitset_count_ones',
            '       │',
            '[پرونده ۱۱]  ─── پرونده نهایی، ترکیب پیمایش گراف با شواهد بیتی',
            '       │',
            '[نتیجه]      ─── ۱۱ از ۱۱ پرونده حل شد — Principal Detective Agent، مدال طلای ۱۰۰٪',
          ],
          methodology: [
            'make-graph: از یال‌های جدولی (SourceMachine، TargetMachine) یک گراف در حافظه می‌سازد تا graph-match بتواند الگوهای مسیر را جست‌وجو کند — تکنیک اصلی برای بازسازی حرکت جانبی میان میزبان‌ها بدون جوین دستی جدول با خودش در هر مرحله.',
            'اپراتور scan: ردیف‌ها را به‌ترتیب ارزیابی می‌کند و حالت را میان آن‌ها منتقل می‌سازد، که تشخیص دنباله‌هایی را ممکن می‌کرد که معنای هر ردیف به ردیف قبلی‌اش وابسته بود — چیزی که یک شرط where بدون حالت نمی‌تواند بیان کند.',
            'bitset_count_ones / binary_and: فیلدهای عدد صحیح فشرده را بیت‌به‌بیت رمزگشایی می‌کند و اجازه می‌دهد یک ستون StatusMask جایگزین چندین شرط بولی هم‌زمان شود؛ سپس ردیفی که الگوی بیتی‌اش با شرط پرونده مطابقت دارد جدا می‌شود.',
          ],
          findings: [
            'هر یازده پرونده تنها با KQL روی کلاستر زنده ADX حل شد، بدون هیچ پردازش داده خارجی.',
            'الگوی مهندسی تکرارشونده در سخت‌ترین پرونده‌ها، ترکیب بازسازی گراف (make-graph) با تشخیص دنباله حالت‌دار (scan) بود — همان ترکیبی که در شکار واقعی حرکت جانبی به کار می‌رود.',
            'رمزگشایی بیت‌مسک (پرونده ۱۰) نشان داد ستون‌های پرچم وضعیت فشرده می‌توانند سیگنالی ساختاریافته و قابل پرس‌وجو را پنهان کنند، نه صرفاً داده‌ای مات.',
          ],
          limitations: 'این یک محیط آموزشی و ارزیابی (Kusto Detective Agency) بود، نه یک حادثه واقعی در محیط عملیاتی — مجموعه‌داده مصنوعی است و رفتار «مهاجم» توسط طراحان پرونده اسکریپت شده است. ارزش این تجربه در مجموعه تکنیک‌های قابل‌انتقال KQL (پیمایش گراف، اسکن حالت‌دار، همبستگی بیتی) است، نه ادعای پاسخ به یک حادثه واقعی.',
          reproduction: 'تاریخچه کامل پرس‌وجوها و یادداشت‌های هر پرونده در ریپازیتوری گیت‌هاب پیوست‌شده منتشر شده است تا هرکس بتواند تحقیق را روی نمونه خودش از فصل دوم Kusto Detective Agency بازتولید کند.',
        },
      },
      hayabusa: {
        title: 'از رویداد لاگ تا تایم‌لاین حمله: گردش‌کار تریاژ ویندوز با Hayabusa',
        description: 'یک گزارش پسامرگ مهندسی ساختاریافته درباره یک نفوذ اولیه شبیه‌سازی‌شده. همبسته‌سازی تله‌متری EVTX، تشخیص‌های قوانین Sigma، لاگ‌های اسکریپت‌بلاک پاورشل و درخت اجرای پردازش‌ها در یک تایم‌لاین قابل تایید.',
        status: 'پژوهش آزمایشگاهی / گزارش پسامرگ',
        content: {
          abstract: 'این گزارش فنی، یک تحقیق کامل فارنزیک دیجیتال و پاسخ به حادثه (DFIR) روی یک ایستگاه‌کاری آلوده‌شده ویندوزی را مستند می‌کند. با استفاده از ابزار تریاژ فارنزیک پرسرعت مبتنی بر Rust به نام Hayabusa، همبسته‌شده با لاگ‌های رویداد امنیتی، سیستمی و اسکریپت‌بلاک پاورشل ویندوز، تایم‌لاین کامل حمله از اجرای اولیه تا برداشت اعتبارنامه و کاوش جانبی بازسازی شد.',
          problem: 'در طول شکار روتین تهدید، یک اتصال خروجی SMB ناهنجار شناسایی شد. آثار لاگ رویداد خام (.evtx) از WORKSTATION-04 جمع‌آوری شد. هدف: تعیین مکانیزم دسترسی اولیه، شجره پردازش‌های فرزند و تایید تلاش‌های دسترسی به اعتبارنامه.',
          environment: [
            'سیستم‌عامل هدف: Windows 10 Enterprise (Build 19045، ۶۴بیتی)',
            'میزبان تحلیل تریاژ: هسته لینوکس ۷.۰ / اوبونتو ۲۴.۰۴',
            'ابزارها: Hayabusa نسخه ۲.۱۷.۰ (مجموعه قوانین Sigma نسخه ۰.۲۲)، EvtxECmd نسخه ۱.۵.۰، نرمال‌ساز سفارشی پایتون',
          ],
          evidence: [
            { event: 'EID 4688 (ایجاد پردازش)', timestamp: '14:22:08.114 UTC', detail: 'WINWORD.EXE فرزند cmd.exe را ایجاد کرد که به‌نوبه خود powershell.exe را با یک آرگومان دستور رمزگذاری‌شده اجرا کرد؛ منطبق با زنجیره اجرای ماکرو فیشینگ.' },
            { event: 'محموله رمزگشایی‌شده', timestamp: '14:22:12.430 UTC', detail: 'Invoke-WebRequest به یک میزبان خارجی، اسکریپت پاورشل مرحله دوم را به مسیر موقت بازیابی و بلافاصله اجرا کرد.' },
            { event: 'دسترسی به handle پردازش LSASS (Sysmon 10)', timestamp: '14:25:31.002 UTC', detail: 'پردازش lsass.exe هدف با یک ماسک دسترسی محدود به خواندن باز شد — الگویی که به‌عنوان تلاش برای دامپ اعتبارنامه پرچم‌گذاری شد.' },
          ],
          timeline: [
            '[14:22:08 UTC] ─── WINWORD.EXE فرزند cmd.exe را ایجاد می‌کند (اجرای ماکرو فیشینگ)',
            '       │',
            '[14:22:12 UTC] ─── پاورشل مرحله دانلود دوم را اجرا می‌کند',
            '       │',
            '[14:23:45 UTC] ─── شناسایی: whoami /all و net user /domain',
            '       │',
            '[14:25:31 UTC] ─── دسترسی به handle پردازش LSASS (تلاش دامپ اعتبارنامه)',
            '       │',
            '[14:26:10 UTC] ─── پردازش توسط EDR خاتمه یافت / میزبان ایزوله شد',
          ],
          methodology: [
            'فاز ۱ — تریاژ پرسرعت با Hayabusa: اجرای hayabusa csv-timeline روی شواهد جمع‌آوری‌شده، فیلترشده در سطح متوسط به بالا.',
            'فاز ۲ — تحلیل اسکریپت‌بلاک پاورشل: فیلتر رویداد شناسه ۴۱۰۴ برای بازیابی اسکریپت‌بلاک‌های ثبت‌شده توسط AMSI و استخراج محموله رمزگشایی‌شده.',
            'فاز ۳ — نگاشت درخت اجرای پردازش: همبستگی والد-فرزند روی رویداد شناسه ۴۶۸۸ با ممیزی کامل خط فرمان.',
          ],
          findings: [
            'علت ریشه‌ای: اجرای ماکرو مخرب، مرحله‌بندی محموله ثانویه را آغاز کرد.',
            'قرارگیری اعتبارنامه در معرض خطر: یک handle خواندن روی LSASS باز شد؛ باطل‌سازی اعتبارنامه لازم بود.',
            'کاوش جانبی: میزبان پیش از موفقیت هرگونه احراز هویت جانبی ایزوله شد.',
          ],
          limitations: 'دامپ حافظه دقیقاً در لحظه تزریق درون‌حافظه‌ای ثبت نشد و ترافیک TLS مربوط به C2 بدون لاگ کلید TLS میزبان بررسی نشد.',
          reproduction: 'یک بسته آزمایشی EVTX پاک‌سازی‌شده در دسترس است. اجرای Hayabusa روی آن با شناسه قانون Sigma مرجع، اطمینان تشخیص را تایید می‌کند.',
        },
      },
    },
    footer: {
      role: 'مهندس شبکه // متخصص زیرساخت',
      copyright: '© ۲۰۲۶ پارسا سریری آجیلی // تمام حقوق محفوظ',
      builtWith: 'ساخته شده با 💙 توسط پارسا سریری آجیلی',
    },
  },
};

const LanguageContext = createContext();

const LANG_STORAGE_KEY = 'parsa_lang';

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const stored = window.localStorage.getItem(LANG_STORAGE_KEY);
    return stored === 'fa' ? 'fa' : 'en';
  });
  const isRTL = lang === 'fa';

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    window.localStorage.setItem(LANG_STORAGE_KEY, lang);
  }, [lang, isRTL]);

  const toggleLang = () => setLang((l) => (l === 'en' ? 'fa' : 'en'));
  const t = translations[lang];

  return (
    <LanguageContext.Provider value={{ lang, isRTL, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}