import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    nav: {
      nexus: 'NEXUS', about: 'ABOUT', stack: 'STACK', trajectory: 'TRAJECTORY', writeups: 'WRITEUPS', connect: 'CONNECT',
      motionOn: 'MOTION: ON', motionOff: 'MOTION: OFF',
    },
    about: {
      label: 'OPERATOR_PROFILE',
      title1: 'ABOUT', title2: 'THE_ARCHITECT',
      bioPath: 'cat about.md',
      bio1: 'I am Parsa Sariri Ajili — a 19-year-old network engineering student with a deep passion for building and securing digital infrastructure.',
      bio2: 'My journey began with hardware and operating systems, evolving into network architecture across Cisco, MikroTik, and Microsoft ecosystems. Along the way, I mastered Linux administration, Python automation, and virtualization technologies.',
      bio3: 'Currently preparing to pivot into cybersecurity — transforming my networking expertise into proactive defense, threat analysis, and impenetrable security architecture.',
      statsCerts: 'CERTIFICATIONS', statsDomains: 'DOMAINS', statsAge: 'YEARS OLD', statsLearning: 'LEARNING',
    },
    hero: {
      systemOnline: 'SYSTEM ONLINE',
      tagline: 'Network Engineering & Cybersecurity Specialist',
      birthTag: 'B.2007.06.16',
      statusTag: 'STATUS: NETWORK_ARCHITECT',
      pivotTag: 'PIVOT → CYBER_SEC',
      viewStack: 'VIEW_STACK',
      initiateContact: 'INITIATE_CONTACT',
      scrollToTraverse: 'SCROLL_TO_TRAVERSE',
    },
    skills: {
      label: 'STACK_HIERARCHY',
      title1: 'CERTIFICATION',
      title2: 'RACK',
      description: 'Each blade represents a layer of technical mastery. Click to inspect the protocols within.',
      rackInfo: '/dev/certification_rack — 10 BLADES MOUNTED',
      masteryPoints: 'MASTERY_POINTS:',
    },
    certs: {
      aplus: { name: 'CompTIA A+', category: 'Infrastructure', mastery: ['Hardware diagnostics', 'PC assembly & repair', 'Mobile devices', 'Operating systems', 'Troubleshooting methodology'] },
      netplus: { name: 'CompTIA Network+', category: 'Networking', mastery: ['OSI & TCP/IP models', 'Subnetting & VLANs', 'Routing & switching', 'Network security basics', 'Wireless protocols'] },
      mcsa: { name: 'Microsoft MCSA', category: 'Microsoft', mastery: ['Windows Server administration', 'Active Directory', 'Group Policy', 'DNS/DHCP on Windows', 'Hyper-V'] },
      lpic1: { name: 'Linux LPIC-1', category: 'Linux', mastery: ['Command-line proficiency', 'File systems & permissions', 'Process management', 'Bash scripting', 'Package management'] },
      pynet: { name: 'Python for Network Engineers', category: 'Programming', mastery: ['Network automation', 'Netmiko & NAPALM', 'API interactions', 'Configuration management', 'Data parsing & analysis'] },
      ccna: { name: 'Cisco CCNA', category: 'Networking', mastery: ['IOS configuration', 'VLANs & trunking', 'OSPF & static routing', 'ACLs & NAT', 'Device security'] },
      mtcna: { name: 'MikroTik MTCNA', category: 'Networking', mastery: ['RouterOS administration', 'Firewall & NAT', 'Wireless & CAPsMAN', 'Hotspot & PPPoE', 'Queues & QoS'] },
      lpic2: { name: 'Linux LPIC-2', category: 'Linux', mastery: ['Advanced system administration', 'Kernel & boot process', 'DNS & mail servers', 'Web services', 'System security hardening'] },
      vcp: { name: 'Virtualization VCP', category: 'Virtualization', mastery: ['VMware vSphere', 'VM lifecycle management', 'Resource pools', 'vMotion & HA', 'Storage management'] },
      bm: { name: 'Backup and Monitoring', category: 'Infrastructure', mastery: ['Backup strategies', 'Disaster recovery', 'Monitoring tools', 'Alerting & thresholds', 'Log analysis'] },
    },
    trajectory: {
      label: 'THE_TRAJECTORY',
      titleFrom: 'FROM', titleNetwork: 'NETWORK', titleTo: 'TO', titleSecurity: 'SECURITY',
      subtitle: 'A continuous evolution — building the infrastructure today, securing it tomorrow.',
      currentState: 'CURRENT_STATE', networkMastery: 'Network Mastery',
      nextVector: 'NEXT_VECTOR', cybersecurity: 'Cybersecurity',
      currentGrid: { routing: 'Routing & Switching', infra: 'Infrastructure', server: 'Server Administration', defense: 'Network Defense' },
      futureGrid: { pentest: 'Penetration Testing', threat: 'Threat Analysis', secArch: 'Sec Architecture', incident: 'Incident Response' },
      currentDesc: 'Currently studying network engineering with deep hands-on expertise across Cisco, MikroTik, Linux, and Microsoft ecosystems. 10 certifications and counting.',
      futureDesc: 'Next phase: diving deep into cybersecurity — transforming network knowledge into impenetrable defense systems and proactive threat intelligence.',
      masteryLevel: 'MASTERY_LEVEL', inProgress: 'IN_PROGRESS',
    },
    contact: {
      label: 'THE_PROTOCOL',
      title1: 'ESTABLISH', title2: 'CONNECTION',
      description: 'Initialize a secure data transmission. All inputs are encrypted and logged.',
      inputName: 'INPUT_NAME:', inputEmail: 'INPUT_EMAIL:', inputMessage: 'INPUT_MESSAGE:',
      namePlaceholder: 'enter your name...', emailPlaceholder: 'enter your email...', messagePlaceholder: 'type your message...',
      execute: 'EXECUTE_SEND', transmitting: 'TRANSMITTING...', complete: 'TRANSMISSION COMPLETE',
      shellPrompt: 'parsa@secure-shell:~$',
      toastTitle: 'TRANSMISSION COMPLETE', toastDesc: 'Message received. I will respond shortly.',
      errorTitle: 'TRANSMISSION FAILED', errorDesc: 'Something went wrong. Please try again.',
    },
    writeups: {
      badge: 'LAB NOTEBOOK // REPRODUCIBLE RESEARCH & THREAT HUNTING',
      title1: 'TECHNICAL INVESTIGATIONS', title2: '& LAB REPORTS',
      subtitle: 'Incident triage, KQL threat hunting across billion-row telemetry, and systems engineering — documented the way it happened, with first-hand evidence and reproducible steps.',
      categories: {
        all: 'ALL',
        threat: 'THREAT HUNTING (KQL)',
        dfir: 'DFIR',
        infra: 'INFRASTRUCTURE',
        malware: 'MALWARE',
      },
      emptyTitle: 'NO_ENTRIES_IN_THIS_CATEGORY',
      emptyDesc: 'Nothing logged here yet — new investigations land in this category as they wrap up.',
      featuredBadge: 'CREDLY 100% GOLD AWARD',
      featuredEyebrow: 'FEATURED CASE FILE',
      readFull: 'Read Full Investigation',
      viewRepo: 'View Repository',
      viewCredential: 'View Credential',
      difficulty: 'Difficulty',
      status: 'Status',
      backToIndex: 'Back to writeups index',
      closeReader: 'Close reader',
      toolsUsed: 'Tools Used',
      sections: {
        abstract: 'Abstract & Executive Summary',
        problem: 'Problem Statement',
        environment: 'Environment & Setup',
        evidence: 'Verifiable Evidence Log',
        timeline: 'Reconstructed Timeline',
        methodology: 'Methodology & KQL Patterns',
        findings: 'Root Cause Findings & Limitations',
      },
      limitationLabel: 'LIMITATION',
      reproductionLabel: 'REPRODUCTION',
      viewAllLink: 'View All Writeups & Lab Notebook',
      catalogBadge: 'FULL CASE INDEX',
      catalogSubtitle: 'Every logged investigation, filterable by discipline.',
      backToWriteups: 'Back to Writeups',
      backHome: 'Back to homepage',
      copyCode: 'Copy',
      copied: 'Copied!',
      credly: {
        verified: 'Verified Credential',
        viewOnCredly: 'View on Credly',
        badgeTitle: 'Kusto Detective Gold Star!',
        issuer: 'Issued by Microsoft Azure Data Explorer',
      },
      credentials: {
        rackLabel: 'VERIFIED CREDENTIALS',
        goldStar: 'Credly Gold Star (100% Award)',
        principalDetective: 'Principal Detective Rank',
        appliedSkills: 'Microsoft Applied Skills — APL-5004 (Defender XDR)',
        verifyAppliedSkills: 'Verify on Microsoft Learn',
        viewAllBadges: 'All 11 Official Microsoft KDA Badges on Credly',
      },
      notFoundTitle: 'CASE_FILE_NOT_FOUND',
      notFoundDesc: 'No investigation is logged at this address. It may have been renamed or archived.',
      metaTitleSuffix: 'Lab Notebook — Parsa Sariri',
      kda: {
        title: 'Echoes of Deception: Solving All 11 Cases of the Kusto Detective Agency, Season 2',
        description: 'A full case log of the Season 2 Azure Data Explorer investigation game — resolving all eleven cases across 2.18M+ MachineLogs rows using graph traversal, stateful sequence matching, and bitwise correlation in KQL.',
        status: 'Case Log / Completed Investigation — 100% Gold Award',
        metrics: {
          cases: 'CASES RESOLVED',
          logs: 'MACHINELOGS TRAVERSED',
          graph: 'LATERAL MOVEMENT MAPPING',
          solver: 'STATEFUL PATTERN SOLVER',
        },
        content: {
          abstract: 'This case log documents the complete resolution of the Kusto Detective Agency Season 2 campaign, "Echoes of Deception" — an eleven-case investigative exercise built on Azure Data Explorer (ADX) and the Kusto Query Language (KQL). Each case supplied a narrative brief and a slice of a shared, multi-million-row telemetry dataset; the task was to isolate the responsible entity, action, or anomaly using nothing but KQL against the live cluster. All eleven cases were solved without external tooling, earning the Principal Detective Agent rank and a 100% Gold Award on Credly.',
          problem: 'The season-long dataset centered on the MachineLogs table — a synthetic but densely structured telemetry stream simulating process activity, authentication events, and inter-machine communication across a fictional network of compromised and clean hosts. Each case narrowed the search space differently: some asked for a single anomalous actor buried in millions of rows, others required reconstructing a multi-hop chain of lateral movement, and a few encoded the answer inside bitmasked flag fields that had to be decoded arithmetically rather than filtered directly.',
          environment: [
            'Platform: Azure Data Explorer (ADX) — Kusto Detective Agency Season 2 cluster',
            'Primary table: MachineLogs (2.18M+ rows across the full season)',
            'Query surface: Kusto Query Language (KQL) only — no external scripting or offline processing',
            'Session tooling: ADX web query editor, saved query history for case reproducibility',
          ],
          evidence: [
            { event: 'Row-scale confirmation', timestamp: 'Season baseline', detail: 'MachineLogs | summarize count() returned a working set of 2,183,441 rows, confirming the dataset required aggregation-first strategies rather than manual row inspection.' },
            { event: 'Lateral movement graph build', timestamp: 'Cases 6-8', detail: 'make-graph SourceMachine --> TargetMachine with edge property Timestamp, followed by graph-match to isolate multi-hop paths matching the case narrative\'s described intrusion chain.' },
            { event: 'Bitmask decode pass', timestamp: 'Case 10', detail: 'extend FlagBits = bitset_count_ones(StatusMask) combined with binary_and() filtering to isolate the single machine whose status flags matched the case\'s hidden condition.' },
          ],
          timeline: [
            '[CASES 1-3] ─── Baseline aggregation & filtering fluency (summarize, where, project)',
            '       │',
            '[CASES 4-5] ─── Time-window correlation across authentication and process events',
            '       │',
            '[CASES 6-8] ─── make-graph + graph-match for multi-hop lateral movement chains',
            '       │',
            '[CASE 9]    ─── scan operator for stateful, order-dependent sequence detection',
            '       │',
            '[CASE 10]   ─── Bitwise decoding of packed status flags with bitset_count_ones',
            '       │',
            '[CASE 11]   ─── Final synthesis case combining graph traversal with bitmask evidence',
            '       │',
            '[RESULT]    ─── 11 / 11 cases resolved — Principal Detective Agent, 100% Gold Award',
          ],
          methodology: [
            'make-graph: builds an in-memory graph from tabular edges (SourceMachine, TargetMachine) so that graph-match can search for path patterns — the core technique for reconstructing lateral movement across hosts without manually joining the table against itself for every hop.',
            'scan operator: evaluates rows in order while carrying state forward between them, which made it possible to detect sequences where the meaning of a row depended on what came immediately before it — something a stateless where clause cannot express.',
            'bitset_count_ones / binary_and: decode packed integer flag fields bit by bit, letting a single StatusMask column stand in for many boolean conditions at once, and isolate the row whose bit pattern matched the case\'s described condition.',
          ],
          findings: [
            'All eleven cases resolved using KQL exclusively against the live ADX cluster, with no external data processing.',
            'The recurring engineering pattern across the hardest cases was graph reconstruction (make-graph) paired with stateful sequence detection (scan) — the same combination used in real lateral-movement threat hunting.',
            'Bitmask decoding (Case 10) proved that dense status-flag columns can hide structured, queryable signal instead of being treated as opaque.',
          ],
          limitations: 'This was a training and assessment environment (Kusto Detective Agency), not a live production incident — the dataset is synthetic and the "adversary" behavior is scripted by the case designers. The value is in the transferable KQL technique set (graph traversal, stateful scanning, bitwise correlation), not in claiming a real-world incident response.',
          reproduction: 'Full query history and case-by-case notes are published in the linked GitHub repository for anyone reproducing the investigation against their own Kusto Detective Agency Season 2 instance.',
        },
      },
      hayabusa: {
        title: 'From Event Log to Attack Timeline: A Reproducible Windows Triage Workflow with Hayabusa',
        description: 'A structured engineering postmortem investigating a simulated initial compromise. Correlating EVTX telemetry, Sigma rule detections, PowerShell script block logs, and process execution trees into a verifiable timeline.',
        status: 'Lab Research / Postmortem',
        content: {
          abstract: 'This technical lab report documents an end-to-end digital forensics and incident response (DFIR) investigation conducted on a compromised Windows workstation. Using high-speed Rust-based forensic triage tooling (Hayabusa) correlated with Windows Security, System, and PowerShell Script Block event logs, the complete attack timeline is reconstructed from initial execution to credential harvesting and lateral probing.',
          problem: 'During routine threat hunting, an anomalous outbound SMB connection was detected. Raw event log artifacts (.evtx) were collected from WORKSTATION-04. Objective: determine the initial access mechanism, child process lineage, and validate credential access attempts.',
          environment: [
            'Target OS: Windows 10 Enterprise (Build 19045, x64)',
            'Triage Analysis Host: Linux Kernel 7.0 / Ubuntu 24.04',
            'Tooling: Hayabusa v2.17.0 (Sigma v0.22 ruleset), EvtxECmd v1.5.0, custom Python normalizer',
          ],
          evidence: [
            { event: 'EID 4688 (Process Creation)', timestamp: '14:22:08.114 UTC', detail: 'WINWORD.EXE spawned cmd.exe -> powershell.exe with an encoded command argument, consistent with a phishing macro execution chain.' },
            { event: 'Decoded payload', timestamp: '14:22:12.430 UTC', detail: 'Invoke-WebRequest against an external host retrieved a second-stage PowerShell script to a temp path and executed it immediately.' },
            { event: 'LSASS handle access (Sysmon 10)', timestamp: '14:25:31.002 UTC', detail: 'Target lsass.exe opened with a read-limited-information access mask — flagged as a credential dumping attempt pattern.' },
          ],
          timeline: [
            '[14:22:08 UTC] ─── WINWORD.EXE spawns cmd.exe (phishing macro execution)',
            '       │',
            '[14:22:12 UTC] ─── PowerShell executes stage-2 download cradle',
            '       │',
            '[14:23:45 UTC] ─── Reconnaissance: whoami /all & net user /domain',
            '       │',
            '[14:25:31 UTC] ─── LSASS handle opened (credential dumping attempt)',
            '       │',
            '[14:26:10 UTC] ─── Process terminated by EDR / host isolated',
          ],
          methodology: [
            'Phase 1 — High-speed triage with Hayabusa: hayabusa csv-timeline against the collected evidence, filtered to medium severity and above.',
            'Phase 2 — PowerShell Script Block analysis: filtering Event ID 4104 for AMSI-logged script blocks to recover the decoded payload.',
            'Phase 3 — Process execution tree mapping: parent-child correlation on Event ID 4688 with full command-line auditing.',
          ],
          findings: [
            'Root cause: malicious macro execution initiated secondary payload staging.',
            'Credential exposure: a read handle was opened against LSASS; credential invalidation was required.',
            'Lateral probing: the host was isolated before any successful lateral authentication occurred.',
          ],
          limitations: 'Memory was not captured at the exact millisecond of in-memory injection, and C2 TLS traffic was left uninspected without a host TLS key log.',
          reproduction: 'A sanitized EVTX test bundle is available. Run Hayabusa against it with the referenced Sigma rule ID to verify detection confidence.',
        },
      },
    },
    footer: {
      role: 'NETWORK ENGINEER // INFRASTRUCTURE SPECIALIST',
      copyright: '© 2026 PARSA SARIRI AJILI // ALL_PROTOCOLS_RESERVED',
      builtWith: 'Built with 💙 by Parsa Sariri Ajili',
    },
  },
  fa: {
    nav: {
      nexus: 'سرآغاز', about: 'درباره من', stack: 'مهارت‌ها', trajectory: 'نقشه راه', writeups: 'گزارش‌های فنی', connect: 'ارتباط',
      motionOn: 'انیمیشن: روشن', motionOff: 'انیمیشن: خاموش',
    },
    about: {
      label: 'شناسنامه فنی',
      title1: 'درباره', title2: 'معمار سیستم',
      bioPath: 'cat about.md',
      bio1: 'من پارسا سریری آجیلی هستم — دانشجوی ۱۹ ساله مهندسی شبکه، متمرکز بر پیاده‌سازی، نگهداری و امنیت زیرساخت‌های انترپرایز.',
      bio2: 'مسیر حرفه‌ای من با شناخت عمیق لایه‌های سخت‌افزار و سیستم‌عامل آغاز شد و به طراحی و معماری شبکه در اکوسیستم‌های سیسکو، میکروتیک و مایکروسافت گسترش یافت. در ادامه، بر مدیریت سرورهای لینوکس، اتوماسیون فرآیندها با پایتون و فناوری‌های مجازی‌سازی مسلط شدم.',
      bio3: 'در حال حاضر در حال گسترش تخصص خود به حوزه امنیت سایبری و مهندسی دفاع فعال هستم؛ با هدف تبدیل دانش شبکه به شکار تهدیدات، تحلیل تله‌متری و معماری سیستم‌های مقاوم در برابر نفوذ.',
      statsCerts: 'گواهینامه تخصصی', statsDomains: 'حوزه فنی', statsAge: '۱۹ سال', statsLearning: 'پژوهش مداوم',
    },
    hero: {
      systemOnline: 'سیستم آماده‌به‌کار',
      tagline: 'مهندس زیرساخت شبکه و تله‌متری امنیت',
      birthTag: 'B.2007.06.16',
      statusTag: 'حوزه اصلی: مهندسی زیرساخت و شبکه',
      pivotTag: 'گسترش تخصصی ← شکار تهدید و تله‌متری',
      viewStack: 'مشاهده مهارت‌ها',
      initiateContact: 'ارسال پیام',
      scrollToTraverse: 'برای پیمایش اسکرول کنید',
    },
    skills: {
      label: 'پشته مهارت‌های فنی',
      title1: 'رک',
      title2: 'گواهینامه‌ها',
      description: 'هر ماژول در این رک نشان‌دهنده تسلط عملیاتی بر یک بخش از زیرساخت است. برای مشاهده جزئیات و مهارت‌ها کلیک کنید.',
      rackInfo: '/dev/certification_rack — ۱۰ ماژول فعال',
      masteryPoints: 'سرفصل‌ها و مهارت‌های کلیدی:',
    },
    certs: {
      aplus: { name: 'CompTIA A+', category: 'زیرساخت', mastery: ['عیب‌یابی سخت‌افزار و معماری سیستم', 'اسمبل و عیب‌یابی کامپیوتر', 'پشتیبانی تجهیزات همراه', 'ساختار سیستم‌عامل‌ها', 'متدولوژی استاندارد ترابل‌شوتینگ'] },
      netplus: { name: 'CompTIA Network+', category: 'شبکه', mastery: ['مدل‌های مرجع OSI و TCP/IP', 'طراحی ساب‌نت و پیاده‌سازی VLAN', 'مسیریابی و سوئیچینگ لایه دو و سه', 'مبانی امنیت شبکه و کنترل دسترسی', 'پروتکل‌های ارتباطی بی‌سیم'] },
      mcsa: { name: 'Microsoft MCSA', category: 'مایکروسافت', mastery: ['مدیریت سرورهای Windows Server', 'طراحی و نگهداری Active Directory', 'اعمال پالیسی‌های سازمانی با Group Policy', 'سرویس‌های شبکه DNS و DHCP', 'مجازی‌سازی با Hyper-V'] },
      lpic1: { name: 'Linux LPIC-1', category: 'لینوکس', mastery: ['تسلط جامع بر خط فرمان و شل Bash', 'سیستم‌های فایل و مدل مجوزهای لینوکس', 'مدیریت پروسس‌ها و سرویس‌های سیستم', 'اسکریپت‌نویسی کاربردی', 'مدیریت بسته‌ها و نرم‌افزارها'] },
      pynet: { name: 'Python for Network Engineers', category: 'برنامه‌نویسی', mastery: ['اتوماسیون پیکربندی تجهیزات شبکه', 'کار با کتابخانه‌های Netmiko و NAPALM', 'ارتباط با APIها و سرویس‌های تحت شبکه', 'مدیریت یکپارچه کانفیگ‌ها', 'پارس و تحلیل داده‌های ساختاریافته'] },
      ccna: { name: 'Cisco CCNA', category: 'شبکه', mastery: ['پیکربندی سوییچ و روتر با Cisco IOS', 'طراحی Trunking و پروتکل‌های STP', 'مسیریابی پیشرفته با OSPF و مسیرهای استاتیک', 'امن‌سازی ترافیک با ACL و NAT', 'سخت‌سازی امنیتی تجهیزات زیرساخت'] },
      mtcna: { name: 'MikroTik MTCNA', category: 'شبکه', mastery: ['مدیریت و راهبری سیستم‌عامل RouterOS', 'پیکربندی فایروال، فیلترینگ و NAT', 'راهکارهای وایرلس و مدیریت متمرکز CAPsMAN', 'راه‌اندازی سرویس‌های Hotspot و PPPoE', 'مدیریت پهنای باند با Simple Queue و QoS'] },
      lpic2: { name: 'Linux LPIC-2', category: 'لینوکس', mastery: ['مدیریت پیشرفته سیستم و منابع لینوکس', 'سفارشی‌سازی کرنل و فرآیند بوت', 'مدیریت سرورهای BIND DNS و سرویس ایمیل', 'استقرار و مانیتورینگ وب‌سرورها', 'سخت‌سازی و امنیت سطح سیستم‌عامل'] },
      vcp: { name: 'Virtualization VCP', category: 'مجازی‌سازی', mastery: ['معماری و استقرار VMware vSphere / ESXi', 'مدیریت چرخه عمر ماشین‌های مجازی', 'تخصیص بهینه با Resource Pools', 'پایداری سرویس با vMotion و vSphere HA', 'مدیریت فضاهای ذخیره‌سازی Datastore'] },
      bm: { name: 'Backup and Monitoring', category: 'زیرساخت', mastery: ['طراحی استراتژی‌های بکاپ ۳-۲-۱', 'برنامه‌ریزی بازیابی بحران (Disaster Recovery)', 'استقرار ابزارهای مانیتورینگ متمرکز', 'تنظیم آستانه‌های هشدار و آلرتینگ هوشمند', 'جمع‌آوری و تجمیع لاگ‌های سیستمی'] },
    },
    trajectory: {
      label: 'نقشه راه حرفه‌ای',
      titleFrom: 'از', titleNetwork: 'زیرساخت شبکه', titleTo: 'به سمت', titleSecurity: 'امنیت سایبری',
      subtitle: 'مسیری پیوسته و هدفمند — ساخت زیرساخت پایدار امروز، صیانت و دفاع تله‌متری فردا.',
      currentState: 'وضعیت کنونی', networkMastery: 'تسلط بر زیرساخت شبکه',
      nextVector: 'افق پیش‌رو', cybersecurity: 'امنیت سایبری و شکار تهدید',
      currentGrid: { routing: 'مسیریابی و سوئیچینگ', infra: 'زیرساخت فیزیکی و ابری', server: 'مدیریت و راهبری سرور', defense: 'دفاع و سخت‌سازی شبکه' },
      futureGrid: { pentest: 'شبیه‌سازی حملات و نفوذ', threat: 'شکار و تحلیل تهدیدات', secArch: 'معماری امنیت انترپرایز', incident: 'پاسخ به رخدادهای سایبری' },
      currentDesc: 'دانشجوی مهندسی شبکه با تسلط عمیق و عملیاتی بر زیرساخت‌های سیسکو، میکروتیک، لینوکس و مایکروسافت، متکی بر ۱۰ گواهینامه تخصصی.',
      futureDesc: 'گام پیش‌رو: ورود متمرکز به کشف و تحلیل نفوذ — پیوند تجربه شبکه با تله‌متری پیشرفته لاگ‌ها و مهندسی دفاع فعال.',
      masteryLevel: 'سطح تسلط فعلی', inProgress: 'در حال توسعه',
    },
    contact: {
      label: 'کانال ارتباطی',
      title1: 'برقراری', title2: 'ارتباط مستقیم',
      description: 'برای طرح پرسش‌های فنی، تبادل نظر پیرامون زیرساخت و تله‌متری یا فرصت‌های همکاری می‌توانید از این بخش پیام ارسال کنید.',
      inputName: 'نام و نام خانوادگی:', inputEmail: 'آدرس ایمیل:', inputMessage: 'متن پیام:',
      namePlaceholder: 'نام خود را وارد کنید...', emailPlaceholder: 'ایمیل معتبر جهت پاسخ...', messagePlaceholder: 'پیام خود را بنویسید...',
      execute: 'ارسال پیام', transmitting: 'در حال ارسال پیام...', complete: 'پیام با موفقیت ارسال شد',
      shellPrompt: 'parsa@secure-shell:~$',
      toastTitle: 'پیام با موفقیت ارسال شد', toastDesc: 'پیام شما دریافت شد و در اسرع وقت پاسخ خواهم داد.',
      errorTitle: 'خطا در ارسال پیام', errorDesc: 'ارسال با مشکل مواجه شد. لطفاً مجدداً تلاش کنید.',
    },
    writeups: {
      badge: 'دفترچه آزمایشگاه // پژوهش‌های فنی و شکار تهدید',
      title1: 'تحقیقات تخصصی', title2: 'و گزارش‌های آزمایشگاهی',
      subtitle: 'تریاژ رخدادهای امنیتی، شکار تهدیدات با KQL روی داده‌های حجیم تله‌متری و مستندسازی گام‌به‌گام سناریوهای انترپرایز همراه با شواهد فنی قابل تایید و تکرارپذیر.',
      categories: {
        all: 'همه موارد',
        threat: 'شکار تهدید (KQL)',
        dfir: 'فارنزیک و پاسخ به رخداد (DFIR)',
        infra: 'زیرساخت و سیستم‌ها',
        malware: 'تحلیل بدافزار',
      },
      emptyTitle: 'موردی در این دسته‌بندی یافت نشد',
      emptyDesc: 'هنوز گزارشی در این بخش ثبت نشده است؛ به محض اتمام پروژه‌های جدید، نتایج منتشر خواهد شد.',
      featuredBadge: 'مدال طلای رسمی مایکروسافت (۱۰۰٪ کامل)',
      featuredEyebrow: 'پرونده ویژه و شاخص',
      readFull: 'مطالعه کامل پرونده',
      viewRepo: 'مشاهده ریپازیتوری در گیت‌هاب',
      viewCredential: 'تایید اصالت مدرک',
      difficulty: 'سطح سناریو',
      status: 'وضعیت پروژه',
      backToIndex: 'بازگشت به فهرست گزارش‌ها',
      closeReader: 'بستن گزارش',
      toolsUsed: 'ابزارها و فناوری‌ها',
      sections: {
        abstract: 'چکیده و جمع‌بندی مدیریتی',
        problem: 'صورت مسئله و ابعاد تهدید',
        environment: 'مشخصات محیط و کلاستر داده',
        evidence: 'لاگ و شواهد فنی قابل تایید',
        timeline: 'گاه‌شمار رخدادها (Timeline)',
        methodology: 'متدولوژی تحلیل و الگوهای KQL',
        findings: 'علت ریشه‌ای (Root Cause) و محدودیت‌ها',
      },
      limitationLabel: 'محدودیت‌های سناریو',
      reproductionLabel: 'تکرارپذیری شواهد',
      viewAllLink: 'مشاهده آرشیو کامل گزارش‌ها و دفترچه آزمایشگاه',
      catalogBadge: 'کاتالوگ جامع پرونده‌ها',
      catalogSubtitle: 'آرشیو تمام تحقیقات و گزارش‌های آزمایشگاهی بر تفکیک حوزه تخصصی.',
      backToWriteups: 'بازگشت به گزارش‌های فنی',
      backHome: 'بازگشت به صفحه اصلی',
      copyCode: 'کپی کد',
      copied: 'کپی شد!',
      credly: {
        verified: 'گواهینامه تاییدشده',
        viewOnCredly: 'مشاهده تاییدیه در Credly',
        badgeTitle: 'Kusto Detective Gold Star!',
        issuer: 'صادرشده توسط Microsoft Azure Data Explorer',
      },
      credentials: {
        rackLabel: 'نشان‌ها و مدارک رسمی تاییدشده',
        goldStar: 'مدال طلای رسمی Credly (اتمام ۱۰۰٪ چالش‌ها)',
        principalDetective: 'رتبه کارآگاه ارشد (Principal Detective)',
        appliedSkills: 'مدرک تخصصی Microsoft Applied Skills: APL-5004 (Defender XDR)',
        verifyAppliedSkills: 'استعلام اصالت در Microsoft Learn',
        viewAllBadges: 'مشاهده هر ۱۱ نشان رسمی KDA مایکروسافت در پلتفرم Credly',
      },
      notFoundTitle: 'پرونده مورد نظر یافت نشد',
      notFoundDesc: 'هیچ مستنداتی در این آدرس وجود ندارد؛ ممکن است گزارش منتقل یا آرشیو شده باشد.',
      metaTitleSuffix: 'دفترچه تحقیقات فنی — پارسا سریری',
      kda: {
        title: 'پژواک فریب: تحلیل جامع و حل ۱۱ پرونده فصل دوم Kusto Detective Agency',
        description: 'مستندات کامل سناریوی تحقیقاتی فصل دوم Azure Data Explorer — بررسی و کشف تهدیدات در بیش از ۲.۱۸ میلیون ردیف تله‌متری لاگ‌های ماشین با استفاده از الگوریتم‌های گراف، تطبیق الگوهای وابسته به حالت و همبستگی بیتی در زبان KQL.',
        status: 'پرونده تکمیل‌شده // مدال طلای رسمی ۱۰۰٪',
        metrics: {
          cases: 'پرونده با موفقیت حل شد',
          logs: 'ردیف لاگ تله‌متری تحلیل شد',
          graph: 'ردیابی گراف حرکت جانبی',
          solver: 'تحلیل الگوی وابسته به حالت',
        },
        content: {
          abstract: 'این گزارش فنی، مستندسازی دقیق حل ۱۱ پرونده از سناریوی تحقیقاتی فصل دوم Kusto Detective Agency تحت عنوان «پژواک فریب» را ارائه می‌دهد. این ارزیابی پیشرفته روی بستر Azure Data Explorer (ADX) و با تکیه بر زبان Kusto Query Language (KQL) انجام گرفته است. در هر پرونده با تکیه بر سناریوی حادثه، داده‌های خام تله‌متری چندمیلیونی مورد واکاوی قرار گرفت تا ردپای نفوذ، رفتارهای مخرب و انحرافات ترافیکی کشف شوند. تمامی پرونده‌ها مستقیماً با کدهای بهینه‌سازی‌شده KQL روی کلاستر زنده مایکروسافت حل شدند و منجر به کسب رتبه Principal Detective Agent و دریافت مدال طلای ۱۰۰٪ در پلتفرم Credly گردید.',
          problem: 'مجموعه‌داده این سناریو روی جدول محوری MachineLogs متمرکز بود؛ جریانی حجیم و ساختاریافته از رویدادهای تولید پروسس، فرآیندهای احراز هویت و ارتباطات بین ماشینی در شبکه‌ای توزیع‌شده. هر پرونده فضای جستجو را به چالشی جدید تبدیل می‌کرد: در برخی موارد کشف یک رفتار مشکوک در میان انبوهی از لاگ‌های نرمال مدنظر بود، در برخی دیگر بازسازی زنجیره چندمرحله‌ای حرکت جانبی (Lateral Movement) مهاجم ضرورت داشت، و در مواردی شواهد درون بیت‌مسک‌های فشرده پنهان شده بودند که نیازمند استخراج ریاضی با عملگرهای بیتی بود.',
          environment: [
            'بستر پردازش: Azure Data Explorer (ADX) — کلاستر رسمی فصل دوم Kusto Detective Agency',
            'جدول مرجع: MachineLogs (بیش از ۲.۱۸ میلیون ردیف داده تله‌متری)',
            'لایه پردازشی: منحصراً Kusto Query Language (KQL) بدون اسکریپت‌های واسط یا پردازش آفلاین',
            'ابزار نشست: کنسول تحت وب ADX همراه با سوابق کوئری‌ها جهت تضمین تکرارپذیری مراحل کشف',
          ],
          evidence: [
            { event: 'بررسی مقیاس کلان تله‌متری', timestamp: 'خط پایه سناریو', detail: 'اجرای کوئری MachineLogs | summarize count() نشان داد با مجموعه‌ای بالغ بر ۲٬۱۸۳٬۴۴۱ ردیف لاگ روبرو هستیم که رویکرد تحلیل دستی را ناممکن ساخته و ضرورت تجمیع بهینه و فیلترینگ تله‌متری را دیکته می‌کرد.' },
            { event: 'مدل‌سازی گراف حرکت جانبی', timestamp: 'پرونده‌های ۶ تا ۸', detail: 'بهره‌گیری از عملگر make-graph برای اتصال ماشین مبدا و مقصد بر پایه زمان رویداد، و سپس اجرای الگوی graph-match جهت ردگیری و جداسازی جهش‌های چندمرحله‌ای مهاجم در شبکه.' },
            { event: 'رمزگشایی بیت‌مسک فشرده', timestamp: 'پرونده ۱۰', detail: 'استفاده از extend FlagBits = bitset_count_ones(StatusMask) همراه با عملگر binary_and() برای استخراج فلگ‌های پنهان وضعیت در سطح بیت و جداسازی میزبان مشکوک.' },
          ],
          timeline: [
            '[پرونده‌های ۱ تا ۳] ─── مهارت‌های پایه در فیلترینگ و تجمیع داده‌های کلان (where, summarize, project)',
            '         │',
            '[پرونده‌های ۴ و ۵] ─── همبسته‌سازی بازه‌های زمانی میان رویدادهای احراز هویت و ایجاد پروسس',
            '         │',
            '[پرونده‌های ۶ تا ۸] ─── به‌کارگیری make-graph و graph-match برای ردیابی زنجیره حرکت جانبی',
            '         │',
            '[پرونده ۹]         ─── بهره‌گیری از عملگر پیشرفته scan جهت کشف الگوهای وابسته به وضعیت و ترتیب زمانی',
            '         │',
            '[پرونده ۱۰]        ─── رمزگشایی ساختار بیتی لاگ‌ها و فیلتر پرچم‌های وضعیت با bitset_count_ones',
            '         │',
            '[پرونده ۱۱]        ─── سناریوی نهایی: ترکیب هم‌زمان تحلیل گراف شبکه با شواهد بیتی تله‌متری',
            '         │',
            '[دستاورد نهایی]     ─── حل ۱۰۰٪ چالش‌ها (۱۱ از ۱۱) — کسب نشان کارآگاه ارشد و مدال طلای Credly',
          ],
          methodology: [
            'عملگر make-graph: ایجاد مدل گراف در حافظه بر اساس یال‌های ترافیکی ماشین‌ها؛ این روش امکان استفاده از دستور قدرتمند graph-match را فراهم می‌کند تا مسیر حرکت مهاجم بدون نیاز به جوین‌های سنگین و تو در تو بازسازی شود.',
            'عملگر scan: ارزیابی ترتیبی رکوردها و حفظ وضعیت در طول لاگ‌ها؛ امکانی حیاتی برای تشخیص حملاتی که هر مرحله از آن وابسته به رخداد قبلی است و با شروط ساده where قابل شناسایی نیست.',
            'توابع بیتی bitset_count_ones و binary_and: رمزگشایی فیلدهای عددی که ده‌ها وضعیت سیستم را در قالب بیت‌مسک فشرده نگهداری می‌کنند؛ این تکنیک امکان استخراج مستقیم سیگنال‌های پنهان را در سطح کوئری مهیا کرد.',
          ],
          findings: [
            'تمامی ۱۱ سناریو بدون هیچ‌گونه پردازش خارجی و صرفاً با ظرفیت پردازشی کوئری‌های استاندارد KQL روی کلاستر ابری حل شدند.',
            'موثرترین الگوی مهندسی در کشف نفوذهای پیچیده، تلفیق ردیابی گرافیکی شبکه (make-graph) با پایش توالی‌های وابسته به وضعیت (scan) بود که مستقیماً در عملیات واقعی شکار تهدید کاربرد دارد.',
            'استخراج موفق نشان داد که فیلدهای فشرده بیتی در تله‌متری ویندوز و لاگ‌های امنیتی، منبعی غنی از داده‌های ساختاریافته برای تشخیص رفتارهای پنهانکارانه هستند.',
          ],
          limitations: 'این پروژه در محیط تخصصی Kusto Detective Agency اجرا شده است؛ داده‌ها شبیه‌سازی‌شده و رفتار سناریو کنترل‌شده بوده است. ارزش اصلی این پرونده‌ها در کاربرد عملیاتی متدهای پیشرفته KQL در محیط‌های واقعی SIEM و پلتفرم‌های تله‌متری داده است.',
          reproduction: 'تمامی کوئری‌ها، متدولوژی استخراج و شواهد گام‌به‌گام هر پرونده در ریپازیتوری مستقل گیت‌هاب منتشر شده و به صورت کامل روی بستر ADX قابل تکرار و اعتبارسنجی است.',
        },
      },
      hayabusa: {
        title: 'تحلیل رویدادهای ویندوز و بازسازی تایم‌لاین حمله با ابزار Hayabusa',
        description: 'گزارش فنی فارنزیک و تریاژ نفوذ شبیه‌سازی‌شده؛ همبسته‌سازی لاگ‌های EVTX، قوانین استاندارد Sigma، لاگ‌های اسکریپت‌بلاک پاورشل و تحلیل درخت اجرای پروسس‌ها در قالب تایم‌لاین دقیق.',
        status: 'پژوهش آزمایشگاهی // گزارش فارنزیک و تریاژ رخداد',
        content: {
          abstract: 'این گزارش فنی، فرآیند پاسخ به حادثه و فارنزیک دیجیتال (DFIR) روی یک ایستگاه کاری ویندوزی آسیب‌دیده را تشریح می‌کند. با استفاده از ابزار سریع Hayabusa (توسعه‌یافته با Rust) و تجمیع آن با لاگ‌های امنیتی، سیستمی و مانیتورینگ پاورشل، تایم‌لاین کامل حمله از مرحله دسترسی اولیه تا استخراج اطلاعات کاربری بازسازی شد.',
          problem: 'در جریان پایش روتین شبکه، ارتباط خروجی مشکوک روی پروتکل SMB شناسایی شد. لاگ‌های خام رویداد ویندوز (.evtx) از سیستم WORKSTATION-04 استخراج شدند تا نحوه ورود اولیه مهاجم، فرآیندهای اجراشده و تلاش‌ها برای دستیابی به دسترسی ادمین مشخص گردد.',
          environment: [
            'سیستم هدف: Windows 10 Enterprise (Build 19045, 64-bit)',
            'محیط تحلیل فارنزیک: لینوکس اوبونتو ۲۴.۰۴',
            'ابزارهای تخصصی: Hayabusa نسخه ۲.۱۷.۰ (قوانین Sigma)، ابزار EvtxECmd و اسکریپت‌های اختصاصی پایتون',
          ],
          evidence: [
            { event: 'رویداد Event ID 4688 (ایجاد پروسس)', timestamp: '14:22:08.114 UTC', detail: 'فرآیند WINWORD.EXE پروسس cmd.exe را اجرا کرد که در ادامه منجر به اجرای پاورشل با دستور رمزگذاری‌شده Base64 شد؛ رفتاری کاملاً منطبق با حمله ماکرو در ایمیل‌های فیشینگ.' },
            { event: 'کشف پی‌لود مرحله دوم', timestamp: '14:22:12.430 UTC', detail: 'دستور Invoke-WebRequest به سرور خارجی متصل شده و اسکریپت تکمیلی را در پوشه موقت ذخیره و بلافاصله اجرا کرد.' },
            { event: 'تلاش برای خواندن پروسس LSASS (Sysmon Event 10)', timestamp: '14:25:31.002 UTC', detail: 'درخواست Handle دسترسی خواندن به حافظه lsass.exe ثبت شد؛ نشانه‌ای قطعی از تلاش برای سرقت هش‌ها و اطلاعات احراز هویت.' },
          ],
          timeline: [
            '[14:22:08 UTC] ─── اجرای ماکرو مخرب در فایل ورد و فراخوانی cmd.exe',
            '         │',
            '[14:22:12 UTC] ─── اجرای اسکریپت پاورشل جهت دانلود پی‌لود مرحله دوم',
            '         │',
            '[14:23:45 UTC] ─── شناسایی محیطی و استعلام اکانت‌های دامین (whoami و net user)',
            '         │',
            '[14:25:31 UTC] ─── تلاش برای دسترسی به حافظه LSASS و استخراج پسوردها',
            '         │',
            '[14:26:10 UTC] ─── متوقف‌سازی پروسس توسط EDR و ایزوله‌سازی موفق میزبان از شبکه',
          ],
          methodology: [
            'فاز ۱ — تریاژ سریع شواهد با Hayabusa: استخراج سریع رخدادهای با اولویت متوسط و بالا بر اساس قوانین Sigma.',
            'فاز ۲ — بررسی لاگ‌های اسکریپت‌بلاک پاورشل: بازرسی رویداد ۴۱۰۴ به کمک لاگ‌های AMSI برای بازسازی دقیق کدهای اجراشده.',
            'فاز ۳ — ترسیم درخت اجرای فرآیندها: ردیابی ارتباط والد-فرزندی پروسس‌ها بر اساس رویداد ۴۶۸۸ و تحلیل خط فرمان کامل.',
          ],
          findings: [
            'منشا ورود اولیه: فایل ورد حاوی ماکرو مخرب منشا فعال‌سازی زنجیره آلودگی بود.',
            'به‌خطر افتادن پسوردها: به دلیل درخواست دسترسی به پروسس LSASS، بازنشانی تمامی سشن‌ها و گذرواژه‌های کاربر الزامی شد.',
            'جلوگیری از نفوذ جانبی: میزبان پیش از اجرای احراز هویت‌های ثانویه در شبکه به طور کامل ایزوله شد.',
          ],
          limitations: 'دامپ کامل حافظه رم در ثانیه‌های اولیه حمله در دسترس نبود و بررسی ترافیک رمزنگاری‌شده C2 به دلیل عدم دسترسی به کلید سشن TLS محدود بود.',
          reproduction: 'مجموعه داده پاک‌سازی‌شده لاگ‌های EVTX به همراه دستورات مشخص ابزار Hayabusa جهت تکرار و اعتبارسنجی یافته‌ها آماده است.',
        },
      },
    },
    footer: {
      role: 'مهندس زیرساخت شبکه // تله‌متری و شکار تهدید',
      copyright: '© ۲۰۲۶ پارسا سریری آجیلی // تمامی حقوق محفوظ است',
      builtWith: 'طراحی و توسعه اختصاصی توسط پارسا سریری آجیلی',
    },
  },
};

const LanguageContext = createContext();

const LANG_STORAGE_KEY = 'parsa_lang';

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const stored = window.localStorage.getItem(LANG_STORAGE_KEY);
    return stored === 'fa' ? 'fa' : 'en';
  });
  const isRTL = lang === 'fa';

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    window.localStorage.setItem(LANG_STORAGE_KEY, lang);
  }, [lang, isRTL]);

  const toggleLang = () => setLang((l) => (l === 'en' ? 'fa' : 'en'));
  const t = translations[lang];

  return (
    <LanguageContext.Provider value={{ lang, isRTL, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}